Repository mezzio/mezzio-skeleton, pull requests merged in 2020-09, with the labels that each got.

#32 Feat: Laminas coding style 2.1
  .gitignore
  .travis.yml
  composer.json
  config/config.php
  phpcs.xml
  phpcs.xml.dist
  phpstan.installer.neon
  src/App/src/Handler/HomePageHandler.php
  src/App/src/Handler/HomePageHandlerFactory.php
  src/App/src/Handler/PingHandler.php
  src/MezzioInstaller/OptionalPackages.php
  src/MezzioInstaller/Resources/config/container-laminas-servicemanager.php
  src/MezzioInstaller/Resources/config/container-php-di.php
  src/MezzioInstaller/Resources/config/error-handler-whoops.php
  src/MezzioInstaller/Resources/config/routes-full.php
  src/MezzioInstaller/Resources/config/routes-minimal.php
  src/MezzioInstaller/Resources/src/ConfigProvider.flat.php
  src/MezzioInstaller/Resources/src/ConfigProvider.modular.php
  src/MezzioInstaller/config.php
  test/AppTest/Handler/HomePageHandlerFactoryTest.php
  test/AppTest/Handler/HomePageHandlerTest.php
  test/AppTest/Handler/PingHandlerTest.php
  test/MezzioInstallerTest/AddPackageTest.php
  test/MezzioInstallerTest/ContainersTest.php
  test/MezzioInstallerTest/CopyResourceTest.php
  test/MezzioInstallerTest/ErrorHandlerTest.php
  test/MezzioInstallerTest/HomePageResponseTest.php
  test/MezzioInstallerTest/OptionalPackagesTestCase.php
  test/MezzioInstallerTest/ProcessAnswersTest.php
  test/MezzioInstallerTest/ProjectSandboxTrait.php
  test/MezzioInstallerTest/PromptForOptionalPackagesTest.php
  test/MezzioInstallerTest/RemoveDevDependenciesTest.php
  test/MezzioInstallerTest/RemoveInstallerTest.php
  test/MezzioInstallerTest/RemoveLineFromStringTest.php
  test/MezzioInstallerTest/RequestInstallTypeTest.php
  test/MezzioInstallerTest/RoutersTest.php
  test/MezzioInstallerTest/SetupDataAndCacheDirTest.php
  test/MezzioInstallerTest/SetupDefaultAppTest.php
  test/MezzioInstallerTest/TemplateRenderersTest.php
  test/MezzioInstallerTest/UpdateRootPackageTest.php
Labels: Enhancement

#31 Fix tests errors
  .travis.yml
  composer.json
  phpunit.xml.dist
  test/AppTest/Handler/HomePageHandlerFactoryTest.php
  test/AppTest/Handler/HomePageHandlerTest.php
  test/AppTest/Handler/PingHandlerTest.php
  test/MezzioInstallerTest/OptionalPackagesTestCase.php
  test/MezzioInstallerTest/ProcessAnswersTest.php
Labels: Bug

#33 Mark supported options in the installer
  src/MezzioInstaller/config.php
Labels: Enhancement

#35 Document installing alternative packages
  README.md
Labels: Documentation
