Repository mezzio/mezzio-skeleton, pull requests merged in 2024-01, with the labels that each got.

#133 Remove pimple as a supported container
  .github/workflows/create-project.yml
  composer.json
  composer.lock
  psalm-baseline.xml
  src/App/src/Handler/HomePageHandler.php
  src/MezzioInstaller/OptionalPackages.php
  src/MezzioInstaller/Resources/config/container-pimple.php
  src/MezzioInstaller/config.php
  test/AppTest/Handler/HomePageHandlerFactoryTest.php
  test/AppTest/InMemoryContainer.php
  test/MezzioInstallerTest/AddPackageTest.php
  test/MezzioInstallerTest/ContainersTest.php
  test/MezzioInstallerTest/ErrorHandlerTest.php
  test/MezzioInstallerTest/HomePageResponseTest.php
  test/MezzioInstallerTest/ProcessAnswersTest.php
  test/MezzioInstallerTest/ProjectSandboxTrait.php
  test/MezzioInstallerTest/PromptForOptionalPackagesTest.php
  test/MezzioInstallerTest/RequestInstallTypeTest.php
  test/MezzioInstallerTest/TemplateRenderersTest.php
Labels: Enhancement, Review Needed

#121 Add composer post install/update hooks to clear config cache
  composer.json
Labels: Enhancement

#135 Bump versions for optional packages
  composer.json
  composer.lock
  src/MezzioInstaller/config.php
Labels: Enhancement

#137 Exclude composer.lock from exported archive to avoid lockfile induced installation failure.
  .gitattributes
Labels: Bug

#136 Keep QA tools after installer is done
  .gitattributes
  psalm-baseline.xml
  psalm.xml.dist
  src/MezzioInstaller/OptionalPackages.php
Labels: Enhancement
